cabal-version:      3.0
name:               beetle
version:            3.4.0

synopsis:           The programming language that embraces bugs
homepage:           https://github.com/bogosorter/beetle
license:            MIT
license-file:       license
author:             bogosorter
maintainer:         luiswbarbosa@gmail.com
category:           Development
build-type:         Simple

common configuration
    default-language: Haskell2010
    default-extensions: OverloadedStrings
    ghc-options:
        -Wall
        -Wno-name-shadowing

library core
    import: configuration

    hs-source-dirs: source
    exposed-modules: AST, Parser, TypeChecker, ASTSimplificator, Closures, Encloser, LLVM, Backend, Errors
    build-depends: base, process, megaparsec, containers, parser-combinators, mtl, text, errata

executable beetle
    import: configuration

    hs-source-dirs: app
    main-is: Main.hs
    other-modules: Arguments
    build-depends: base, containers, process, filepath, directory, megaparsec, core

test-suite tests
    import: configuration

    type: exitcode-stdio-1.0
    hs-source-dirs: tests
    main-is: Main.hs
    other-modules: SimpleCompiler
    build-depends: base, process, tasty, tasty-hunit, megaparsec, directory, filepath, extra, core
